apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: egress-gateway
  namespace: gloo-mesh
spec:
  clientMode:
    tlsTermination: {}
  hosts:
  - istio-egressgateway-1-16.global
  ports:
  - number: 80
    protocol: HTTP
    targetPort:
      name: http2
  services:
  - cluster: cluster1
    labels:
      istio: egressgateway
