apiVersion: networking.gloo.solo.io/v2
kind: ExternalEndpoint
metadata:
  labels:
    endpoint: httpbin
  name: httpbin-external-endpoint
  namespace: app1-configs
spec:
  address: httpbin.org
  ports:
  - name: http
    number: 80
  - name: https
    number: 443
