apiVersion: networking.gloo.solo.io/v2
kind: ExternalService
metadata:
  labels:
    service: httpbin
  name: httpbin-external-service
  namespace: gloo-mesh
spec:
  hosts:
  - httpbin.org
  ports:
  - name: http
    number: 80
    protocol: HTTP
  selector:
    endpoint: httpbin
