apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: httpbin-external
  namespace: app1-configs
spec:
  clientMode:
    tlsTermination: {}
  externalServices:
  - labels:
      service: httpbin
  hosts:
  - httpbin.external
  ports:
  - number: 80
    protocol: HTTP
